# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install Julia
      run: |
        mkdir -p julia
        curl -s https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.0-linux-x86_64.tar.gz | tar xzvf - -C julia/
        sudo ln -s "$(pwd)"/julia/julia-1.4.0/bin/julia /usr/local/bin/julia
      shell: bash
      
    - name: Canary job (for now). TODO Setup tests!
      run: |
        cd "$GITHUB_WORKSPACE" && echo "hello world" | julia psst.jl words
        
